### ISSUE TITLE
问下支持win10吗？

### ISSUE THREAD

**Issue by zysNLP** [yandenghong/KortURL#1]
你好，想问下这个工具可以在win10下使用么？
另外，如果部署在服务器中怎么实现可视化，没有ubuntu图形界面。
还有，这个工具可以锁定追踪某个用户么？比如对于访问某页面的一个用户，持续追踪其走向？

**Comment by yandenghong** [comment]
你好，在win10下是可以部署的，但用于增加并发能力的uwsgi和nginx均不能支持win10, win10的部署方式可以看看这篇文章https://blog.csdn.net/qq_32740675/article/details/80265849

部署在服务器上后，只是一个本地的服务，通俗的讲，Web服务器传送页面使浏览器可以浏览，然而应用程序服务器提供的是客户端应用程序可以调用的方法。django虽然也有一个支持http协议的服务器，但并发能力很弱，它只是用于开发时在本地调试。通常在生产环境下都是要专门的性能强劲的web服务器来提供服务，比如nginx。配置好域名，指向服务所在的服务器。即可通过域名在浏览器中访问页面。

锁定追踪用户功能目前尚未支持，只提供了针对url的追踪。后续会考虑把这个功能加入。感谢你的建议!
